apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fred
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: external
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.frontend.domain }}
spec:
  rules:
  - host: {{ .Values.frontend.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fred
            port:
              name: http
